### ISSUE TITLE
参数配置的疑问

### ISSUE THREAD

**Issue by nary24** [shuhanghang/cdn-auto-cert#2]
大佬能否再详细写一下教程呢
比如配置文件中的一些值该怎么获取，最好是能提供一些示例
secret.py
zerossl密钥
## 当使用其他机构申请的证书上传到cdn报证书链错误时，推荐使用zerossl申请证书
ZeroSSL_KID = ""
ZeroSSL_HMAC = ""

# cdn 供应商api访问秘钥变量
## tencent
SecretId = ""
SecretKey = ""
## aliyun
accessKey = ""
accessSecret = ""
## huawei
ak = ""
sk = ""

# dns 供应商api访问秘钥变量 (名称参考 https://go-acme.github.io/lego/dns/)
## aliyun
ALICLOUD_ACCESS_KEY = ""
ALICLOUD_SECRET_KEY = ""

**Comment by shuhanghang** [comment]
更新了secret.py文件的备注说明，您看看还有什么问题吗

**Comment by nary24** [comment]
好的，感谢大佬
