### ISSUE TITLE
连接阿里云的cdn时候，请求的区域不对导致的cdn找不到

### ISSUE THREAD

**Issue by majq1990** [shuhanghang/cdn-auto-cert#3]
cdn加速域名cname检查: 执行失败，HTTP Status: 403 Error:CdnServiceNotFound Your account does not open CDN service yet. RequestID: BA333FB8-2044-500C-B66A-242897F4708E

在阿里云检查发现，cdn的地域错误，我们用的是北京区域的cdn，实际请求是杭州区域：
![image](https://github.com/shuhanghang/cdn-auto-cert/assets/29979847/59039eeb-d219-43d7-9571-def1a6f3df0a)

**Comment by shuhanghang** [comment]
你好，启用前请先确定你的CDN服务是否开通，你配置的CDN加速域名是否属于自己的账号！
[阿里云公共错误码]https://help.aliyun.com/zh/cdn/developer-reference/api-cdn-2018-05-10-errorcodes
