### ISSUE TITLE
可以支持不同的阿里云ak/sk吗？

### ISSUE THREAD

**Issue by wupinlang** [shuhanghang/cdn-auto-cert#4]
我有很多个域名需要配置，不同域名在不同的阿里云账号下面。
可以支持不同的阿里云ak/sk吗？

**Comment by shuhanghang** [comment]
如果涉及的账号不是很多建议部署多套、或则使用[域名转移至其他阿里云账号](https://help.aliyun.com/zh/dws/user-guide/transfer-the-domain-name-to-another-alibaba-cloud-account/?spm=a2c4g.11186623.0.0.5db7186aQtl6bj) 。
暂时不会更新，现在手里没有域名做测试，如果更新可能即时会做一个大改。

**Comment by wupinlang** [comment]
> 如果涉及的账号不是很多建议部署多套、或则使用[域名转移至其他阿里云账号](https://help.aliyun.com/zh/dws/user-guide/transfer-the-domain-name-to-another-alibaba-cloud-account/?spm=a2c4g.11186623.0.0.5db7186aQtl6bj) 。 暂时不会更新，现在手里没有域名做测试，如果更新可能即时会做一个大改。

好的谢谢，我有各种阿里云/腾讯云的账号，属于不同的客户所以没办法做转移。
