### ISSUE TITLE
可以支持dcdn全站加速吗

### ISSUE THREAD

**Issue by majq1990** [shuhanghang/cdn-auto-cert#5]
如题

**Comment by shuhanghang** [comment]
支持阿里云和腾讯云的全站加速

**Comment by majq1990** [comment]
阿里云的全站加速需要咋配置呢?我配置了，发现请求的是阿里云的cdn，而不是全站加速，会提示没有相关的资源供操作

**Comment by majq1990** [comment]
开始会报错2024-07-29 10:45:20.789 | ERROR    | utils.cdn_handler.cdn_handler:cdn_domain_cname_check:27 - cdn加速域名cname检查: 执行失败，HTTP Status: 403 Error:CdnServiceNotFound Your account does not open CDN service yet. RequestID: 194EA039-F39A-5419-A458-5FDF0B77E908

然后当天晚上23点，会自动更新，完成dcdn的获取
![image](https://github.com/user-attachments/assets/8f8ab910-b922-43c1-a59b-de393e5ce1a1)
